# Generated by Django 5.0.6 on 2024-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0002_record_economics_alter_record_physics'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicsMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
            ],
        ),
    ]
