# Generated by Django 5.0.6 on 2024-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0004_economicsans_physicsans'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicsmcq',
            name='ans',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='physicsmcq',
            name='ans',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
