# Generated by Django 5.0.6 on 2024-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0005_economicsmcq_ans_physicsmcq_ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomicsAns',
        ),
        migrations.DeleteModel(
            name='PhysicsAns',
        ),
        migrations.AddField(
            model_name='record',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
