# Generated by Django 5.0.6 on 2024-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0007_rename_current_record_currentphys'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='currentecon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='econdone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='physdone',
            field=models.IntegerField(default=0),
        ),
    ]
