# Generated by Django 5.0.6 on 2024-06-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0008_record_currentecon_record_econdone_record_physdone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='econdone',
            new_name='econsolved',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='physdone',
            new_name='physsolved',
        ),
    ]
