# Generated by Django 5.0.6 on 2024-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0012_economicsstats_physicsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='econlast',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='physlast',
            field=models.DateTimeField(null=True),
        ),
    ]
