# Generated by Django 5.0.6 on 2024-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0013_record_econlast_record_physlast'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ovrlast',
            field=models.DateTimeField(default='2024-06-09 00:00:00'),
        ),
        migrations.AlterField(
            model_name='record',
            name='econlast',
            field=models.DateTimeField(default='2024-06-09 00:00:00'),
        ),
        migrations.AlterField(
            model_name='record',
            name='physlast',
            field=models.DateTimeField(default='2024-06-09 00:00:00'),
        ),
    ]
