# Generated by Django 5.0.6 on 2024-06-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0015_alter_record_econlast_alter_record_ovrlast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='totalsolved',
            field=models.IntegerField(default=0),
        ),
    ]
