# Generated by Django 5.0.6 on 2024-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0016_record_totalsolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologyMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
                ('ans', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BiologyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChemistryMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
                ('ans', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChemistryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='placeholder.png', max_length=64)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
            ],
        ),
    ]
