# Generated by Django 5.0.6 on 2024-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0017_biologymcq_biologystats_chemistrymcq_chemistrystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='biolsolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='biolwrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='canchangename',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='chemsolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='chemwrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='econwrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='physwrong',
            field=models.IntegerField(default=0),
        ),
    ]
