# Generated by Django 5.0.6 on 2024-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0019_record_concord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='canchangename',
        ),
        migrations.AddField(
            model_name='record',
            name='yeargroup',
            field=models.TextField(default='Not assigned', max_length=255),
        ),
    ]
