# Generated by Django 5.0.6 on 2024-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0020_remove_record_canchangename_record_yeargroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='yeargroup',
            field=models.CharField(default='Not assigned', max_length=255),
        ),
    ]
