# Generated by Django 5.0.6 on 2024-06-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0021_alter_record_yeargroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='concord',
            new_name='official',
        ),
    ]
